### ISSUE TITLE
Does not install with zef

### ISSUE THREAD

**Issue by lizmat** [p6steve/perl6-Physics-Measure#9]
Did you actually add this module to the ecosystem, or upload to CPAN?

**Comment by p6steve** [comment]
yep - i tested 
zef install Physics::Measure

test is quite large / slow suggest —verbose

~ Steve

p6steve@furnival.net

**Comment by lizmat** [comment]
$ zef install Physics::Measure
    ===> Searching for: Physics::Measure
    ===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    ===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
    ===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
    ===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
    No candidates found matching identity: Physics::Measure

**Comment by p6steve** [comment]
Thanks - I’ll check PAUSE tonight (uk)

~ Steve

p6steve@furnival.net

**Comment by p6steve** [comment]
Hmmm- works for me (see below) - however, cpan only has it under https://www.cpan.org/modules/by-authors/id/P/PS/PSIXSTEVE/Perl6/perl6-Physics-Measure-0.0.2.tar ... not placed in /Perl6 category or in long list as yet. I suspect I should have uploaded a .tar.gz instead of a plain .tar - let me try that. Probably should wait +1 day...

Jester:~ stephenroe$ zef install Physics::Measure
===> Searching for: Physics::Measure
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Testing: Physics::Measure:ver<0.0.2>:auth<github:p6steve>:api<1>
===> Testing [OK] for Physics::Measure:ver<0.0.2>:auth<github:p6steve>:api<1>
===> Installing: Physics::Measure:ver<0.0.2>:auth<github:p6steve>:api<1>

4 bin/ scripts [svg.html RectMath.p6 P--sics.p6 TriMath.p6] installed to:
/usr/local/Cellar/rakudo-star/2019.03/share/perl6/site/bin

**Comment by p6steve** [comment]
The uploaded file

   perl6-Physics-Measure-0.0.2.tar.gz

has entered CPAN as

 file: $CPAN/authors/id/P/PS/PSIXSTEVE/Perl6/perl6-Physics-Measure-0.0.2.tar.gz
 size: 150887 bytes
  md5: d85dd120cb39dc8daee3980c6d862321
 sha1: 62e2ad1c25cde2474825299d3f48a62a5fa3b036

No action is required on your part

Request entered by: PSIXSTEVE (Steve Roe)
Request entered on: Tue, 30 Jul 2019 18:36:45 GMT
Request completed:  Tue, 30 Jul 2019 18:37:04 GMT

Thanks,
-- 
paused, v1049

**Comment by p6steve** [comment]
Update - I just checked PAUSE Show Files and it looks like the extract and load is going forward since the Readme.md has now correctly been pulled out. While zef uninstall/install works for me - that maybe because I have the files cached. Not however arrived in the long list or the Perl6 category. Suggest we wait another +1 day and check the Perl6 or long list again.

**Comment by lizmat** [comment]
Installed fine for me now, so closing!
